version: '3.8'

services:
  # Service untuk Laravel Application
  app:
    image: php:8.0-fpm
    container_name: laravel_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
    working_dir: /var/www/html
    ports:
      - "9000:9000"

  # Service untuk Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - app

  # Service untuk MySQL Database
  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Service untuk Redis
  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - app-network

# Network yang akan digunakan oleh semua service
networks:
  app-network:
    driver: bridge

# Volume untuk MySQL persistence
volumes:
  mysql_data:
